Added Cart and Order Details (Both Web and mobile view)
AnnLe4869/dormit-second-prototype pull request #5
Opened 2022-07-23 02:07 UTC by mohakvni

2022-07-23 07:09 UTC, AnnLe4869 requested changes
Besides all the comments I made, your code has inconsistent spacing. For example, do you want to have spaces before equal signs? In VSCode there is an extension called Prettier that can do formatting for you. https://prettier.io/docs/en/why-prettier.html

2022-07-23 07:51 UTC, mohakvni commented on src/routes/checkout/Cart.js
> +            'position':'absolute',
Gotcha, will do so

2022-07-23 07:51 UTC, mohakvni commented on src/routes/checkout/Cart.js
> +const closedstore = () => {
Noted.

2022-07-23 07:52 UTC, mohakvni commented on src/routes/checkout/Cart.module.css
> +.buttonnum {
As far as I have tested, it should work on all the screens. If later on required, will change everything to percentage

2022-08-02 00:43 UTC, closed without merging

2022-08-02 00:44 UTC, AnnLe4869 commented
Close and move the PR to another branch